services:
  citybuild:
    image: itzg/minecraft-server:java21
    container_name: citybuild-paper
    ports:
      - "${MC_PORT:-25565}:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"
      MEMORY: "${MC_MEMORY:-4G}"
      ONLINE_MODE: "${MC_ONLINE_MODE:-false}"
      OPS: "${MC_OPS:-}"
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_PROTECTION: "0"
      ENABLE_ROLLING_LOGS: "true"
      TZ: "Europe/Berlin"
    volumes:
      - ./server:/data
      - ./skript:/data/plugins/Skript/scripts/citybuild
    tty: true
    stdin_open: true
    restart: unless-stopped
